certificate:
  title: "Certificado de Participação"
  body: >-
    Certificamos que %NOME_PESSOA% participou da atividade %NOME_ATIVIDADE% com carga
    horária de %DURACAO% horas, no dia %DATA%.
  place.and.date: "São Paulo, %HOJE%"
  token.guide: "Autenticidade pode ser verificada em https://www.dasiusp.com/certificado"
  token.text: "Código de autenticidade: %TOKEN%"

project.id: "cleber-244103"

email:
  from: "DASI-USP <no-reply@dasiusp.com>"
  attachment.name: "Certificado.pdf"
  subject: "Certificado de Participação - %NOME_ATIVIDADE%"
  body: |-
    Olá, %NOME_PESSOA%!

    Agradecemos a sua participação em %NOME_ATIVIDADE%!

    Aqui está o seu certificado de participação. Esperamos você em nossa próxima atividade!

    Atenciosamente,
    DASI-USP

firestore:
  certificate.collection: "certificate"